[build]
  publish = "build"         # or "dist" depending on your framework
  command = "npm run build" # adjust as needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  CI = "false"
